In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]

In [8]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
X_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.78605122 0.80843259 0.78879793 0.80798709
        nan        nan 0.79983167 0.8113136  0.77983876 0.81222124
        nan        nan 0.79072762 0.80745701 0.79549138 0.80717698
        nan        nan 0.793066   0.80498797 0.78807263 0.8092291 ]
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
result=grid.cv_results_
print("R_Score Value for BEST parameter {}".format(grid.best_params_))

R_Score Value for BEST parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}

In [15]:
table=pd.DataFrame.from_dict(result)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002731,0.000063,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.003686,0.000911,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.074270,0.008131,0.009323,0.001508,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.836896,0.764228,0.777117,0.809818,0.742197,0.786051,0.033554,15
3,0.509772,0.005155,0.037800,0.002360,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.864525,0.787383,0.799025,0.818139,0.773091,0.808433,0.031690,4
4,0.073489,0.002360,0.009313,0.000896,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.849251,0.770807,0.765577,0.802809,0.755544,0.788798,0.034116,13
5,0.510834,0.005599,0.036799,0.004196,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.865058,0.787579,0.796137,0.816211,0.774951,0.807987,0.031537,5
6,0.001843,0.000341,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.001902,0.000337,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.132882,0.007909,0.007808,0.000820,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.826035,0.785299,0.797505,0.825657,0.764663,0.799832,0.023694,9
9,1.269444,0.021061,0.035169,0.001769,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.859126,0.795508,0.807237,0.820703,0.773994,0.811314,0.028402,2
10,0.131356,0.004167,0.007369,0.000158,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.815219,0.740750,0.794408,0.807051,0.741764,0.779839,0.032194,16
11,1.296421,0.022941,0.035439,0.001359,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.867182,0.791791,0.806920,0.823139,0.772074,0.812221,0.032240,1
12,0.001542,0.000038,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.002028,0.000750,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.054468,0.001626,0.007642,0.000420,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.861572,0.757988,0.785913,0.784828,0.763337,0.790728,0.037146,12
15,0.483739,0.010055,0.035365,0.001192,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.863664,0.784795,0.792219,0.822535,0.774072,0.807457,0.032394,6
16,0.054617,0.003146,0.007846,0.001537,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.855760,0.767990,0.786622,0.811505,0.755580,0.795491,0.035544,10
17,0.496144,0.011687,0.038974,0.003224,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859621,0.786890,0.796681,0.822215,0.770478,0.807177,0.031129,7
18,0.001605,0.000180,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001647,0.000310,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.058884,0.001715,0.007300,0.000104,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.855251,0.746060,0.801119,0.804039,0.758860,0.793066,0.038553,11
21,0.527302,0.018539,0.032119,0.003391,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.862322,0.785205,0.791832,0.817932,0.767649,0.804988,0.032904,8
22,0.079941,0.006257,0.009918,0.001912,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.840342,0.768995,0.768323,0.806875,0.755828,0.788073,0.031239,14
23,0.480388,0.017342,0.027293,0.003258,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.861870,0.787493,0.803023,0.823663,0.770097,0.809229,0.031691,3

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 36
Children: 1
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣,change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[47333.985]