In [53]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset).astype(int)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children', 'smoker_no','smoker_yes','sex_female','sex_male']]

In [6]:
independent

      age  bmi  children  smoker_no  smoker_yes  sex_female  sex_male
0      19   27         0          0           1           1         0
1      18   33         1          1           0           0         1
2      28   33         3          1           0           0         1
3      33   22         0          1           0           0         1
4      32   28         0          1           0           0         1
...   ...  ...       ...        ...         ...         ...       ...
1333   50   30         3          1           0           0         1
1334   18   31         0          1           0           1         0
1335   18   36         0          1           0           1         0
1336   21   25         0          1           0           1         0
1337   61   29         0          0           1           1         0

[1338 rows x 7 columns]

In [7]:
dependent=dataset[['charges']]

In [8]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
dataset

      age  bmi  children  charges  sex_female  sex_male  smoker_no  smoker_yes
0      19   27         0    16884           1         0          0           1
1      18   33         1     1725           0         1          1           0
2      28   33         3     4449           0         1          1           0
3      33   22         0    21984           0         1          1           0
4      32   28         0     3866           0         1          1           0
...   ...  ...       ...      ...         ...       ...        ...         ...
1333   50   30         3    10600           0         1          1           0
1334   18   31         0     2205           1         0          1           0
1335   18   36         0     1629           1         0          1           0
1336   21   25         0     2007           1         0          1           0
1337   61   29         0    29141           1         0          0           1

[1338 rows x 8 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
X_train

array([[-1.5330973 , -0.36100765, -0.89833872, ..., -0.50466988,
         0.97676557, -0.97676557],
       [-0.03364163,  0.278355  , -0.89833872, ..., -0.50466988,
         0.97676557, -0.97676557],
       [ 0.89459283,  2.51612426,  3.25603402, ..., -0.50466988,
         0.97676557, -0.97676557],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872, ..., -0.50466988,
        -1.02378711,  1.02378711],
       [-1.46169465,  0.75787698, -0.89833872, ..., -0.50466988,
        -1.02378711,  1.02378711],
       [-0.46205754, -1.95941426, -0.06746417, ..., -0.50466988,
         0.97676557, -0.97676557]])

In [45]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1.0)
regressor.fit(X_train,Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=10000.0)

In [46]:
y_pred=regressor.predict(X_test)

In [47]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_pred)

In [48]:
r_score

0.8767270957371092

In [49]:
import pickle
fileName="final_SVM_2_rbf_c10000_Model.sav"
pickle.dump(regressor,open(fileName,'wb'))

In [50]:
load_model=pickle.load(open("final_SVM_2_rbf_c10000_Model.sav",'rb'))

In [51]:
age=int(input("Enter your age : "))
bmi=float(input("Your bmi : "))
children=int(input("Enter the number of children you have : "))
smoker_yes_or_no=input("Enter 'yes' if you are a smoker or 'no' : ")
if smoker_yes_or_no=='yes':
    smoker_yes=1
    smoker_no=0
else:
    smoker_yes=0
    smoker_no=1
sex=input("Enter your sex : ")
if sex=='f':
    sex_female=1
    sex_male=0
else:
    sex_female=0
    sex_male=1

result=load_model.predict([[age,bmi,children,smoker_no,smoker_yes,sex_female,sex_male]])

Enter your age :  35
Your bmi :  6.4
Enter the number of children you have :  2
Enter 'yes' if you are a smoker or 'no' :  yes
Enter your sex :  m

In [52]:
result

array([18156.7785266])