In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [7]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]

In [9]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [10]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [13]:
X_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [20]:
result=grid.cv_results_
print("R_Score Value for BEST parameter {}".format(grid.best_params_))

R_Score Value for BEST parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}

In [23]:
table=pd.DataFrame.from_dict(result)

In [24]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.099654,0.021282,0.036843,0.001771,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004062,0.013335,-0.103476,-0.095366,-0.101569,-0.056603,0.053466,35
1,0.069743,0.003228,0.015330,0.001385,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.055924,0.069452,-0.045421,-0.025445,-0.049485,0.001005,0.051196,32
2,0.089674,0.004479,0.018196,0.000427,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.050024,0.076009,-0.046805,-0.041071,-0.046774,-0.001724,0.053536,34
3,0.066811,0.002480,0.013698,0.000821,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377724,0.479574,0.317907,0.338157,0.324423,0.367557,0.059735,25
4,0.076485,0.002132,0.037021,0.000483,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004135,0.013210,-0.103428,-0.095408,-0.101569,-0.056612,0.053448,36
5,0.067243,0.002218,0.014372,0.000262,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054577,0.071249,-0.046156,-0.024590,-0.049471,0.001122,0.051442,31
6,0.082955,0.002462,0.017587,0.001484,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049754,0.076446,-0.046990,-0.040903,-0.046771,-0.001693,0.053617,33
7,0.067103,0.001438,0.013253,0.000994,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377724,0.479574,0.317907,0.338157,0.324423,0.367557,0.059735,25
8,0.078720,0.003655,0.037396,0.002580,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300124,0.339544,0.174257,0.217017,0.183337,0.242856,0.065642,29
9,0.072846,0.002635,0.014885,0.000793,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.537814,0.574688,0.470001,0.532987,0.425034,0.508105,0.053456,22
10,0.092407,0.006754,0.017975,0.000555,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.482712,0.560842,0.433137,0.449720,0.431324,0.471547,0.048307,23
11,0.086970,0.006788,0.013691,0.000506,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584840,0.656088,0.553185,0.577115,0.547448,0.583735,0.038807,19
12,0.084313,0.002098,0.036228,0.000535,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.300606,0.338790,0.174699,0.216705,0.183330,0.242826,0.065439,30
13,0.082154,0.005526,0.014147,0.000418,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.534189,0.579262,0.467718,0.534956,0.425072,0.508240,0.054754,21
14,0.094304,0.008478,0.017562,0.000575,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.481175,0.561849,0.429295,0.451834,0.431336,0.471098,0.049065,24
15,0.075392,0.003673,0.013923,0.000732,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584840,0.656088,0.553185,0.577115,0.547448,0.583735,0.038807,19
16,0.095557,0.001408,0.037107,0.001499,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.731988,0.743653,0.686787,0.715193,0.644532,0.704430,0.035532,12
17,0.094781,0.005309,0.014667,0.000729,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.830806,0.806043,0.799112,0.802509,0.739945,0.795683,0.030020,7
18,0.093465,0.004691,0.017926,0.000933,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.323851,0.371445,0.287282,0.286805,0.351347,0.324146,0.033854,27
19,0.093396,0.006073,0.013867,0.000546,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.604973,0.589001,0.623195,0.538195,0.617342,0.594541,0.030513,17
20,0.094096,0.001541,0.035898,0.001407,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.732239,0.743319,0.687028,0.715059,0.644529,0.704435,0.035467,11
21,0.100795,0.009590,0.014169,0.000380,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.829390,0.805648,0.798663,0.802669,0.739952,0.795264,0.029659,8
22,0.093545,0.003268,0.017617,0.000582,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.328341,0.386884,0.216176,0.287478,0.351327,0.314041,0.058624,28
23,0.093440,0.004886,0.013420,0.000263,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.604973,0.589001,0.623195,0.538195,0.617342,0.594541,0.030513,17
24,0.102898,0.003507,0.035730,0.001082,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.816190,0.779806,0.791733,0.791076,0.732585,0.782278,0.027540,10
25,0.168596,0.027025,0.014027,0.000319,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.847468,0.808587,0.813767,0.803786,0.755123,0.805746,0.029596,3
26,0.093072,0.003927,0.017746,0.000488,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.445302,-0.511012,-0.493784,-0.461297,-0.099723,-0.402223,0.153017,37
27,0.112415,0.006899,0.013985,0.000278,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605615,0.583248,0.697406,0.532387,0.681584,0.620048,0.061673,15
28,0.102411,0.004273,0.035963,0.000976,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.816457,0.779685,0.791839,0.790950,0.732583,0.782303,0.027609,9
29,0.178659,0.038604,0.014337,0.000386,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.847539,0.808183,0.813734,0.803711,0.755123,0.805658,0.029608,4
30,0.092839,0.003371,0.018088,0.000763,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.616220,-0.532822,-0.478194,-0.542484,-0.102534,-0.454451,0.181367,38
31,0.112932,0.006102,0.013706,0.000404,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605615,0.583248,0.697406,0.532387,0.681584,0.620048,0.061673,15
32,0.108300,0.003325,0.036059,0.001047,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.829220,0.791264,0.810701,0.809750,0.742128,0.796613,0.029771,6
33,0.223033,0.072170,0.013878,0.001816,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.850124,0.806758,0.814590,0.804422,0.757864,0.806752,0.029455,1
34,0.097084,0.002549,0.018199,0.000569,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.754076,-2.044957,-1.699509,-1.914567,-1.035870,-1.689796,0.348857,40
35,0.133681,0.011007,0.014078,0.000784,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657721,0.583243,0.697893,0.529476,0.655869,0.624840,0.060341,13
36,0.112608,0.007269,0.035745,0.000409,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.829352,0.791147,0.810772,0.809730,0.742127,0.796625,0.029809,5
37,0.207308,0.033952,0.010401,0.002947,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.850157,0.806802,0.814553,0.804154,0.757866,0.806706,0.029467,2
38,0.097124,0.003898,0.016250,0.001416,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.682090,-1.830750,-1.676185,-1.941103,-1.036223,-1.633270,0.314468,39
39,0.111633,0.005033,0.011380,0.002149,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657721,0.583243,0.697893,0.529476,0.655869,0.624840,0.060341,13

In [25]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 36
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [27]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣,change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[5879939.43342998]