In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]

In [8]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [12]:
X_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [14]:
result=grid.cv_results_

grid_predictions=grid.predict(X_test)

from sklearn.metrics import r2_score
r_score=r2_score(Y_test,grid_predictions)

print("R_Score Value for BEST parameter {}".format(grid.best_params_),r_score)

R_Score Value for BEST parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'poly'} 0.8580853288879959

In [15]:
table=pd.DataFrame.from_dict(result)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.098212,0.005058,0.036276,0.001815,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004062,0.013335,-0.103476,-0.095366,-0.101569,-0.056603,0.053466,35
1,0.077374,0.004090,0.015100,0.001077,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.055924,0.069452,-0.045421,-0.025445,-0.049485,0.001005,0.051196,32
2,0.102340,0.013635,0.017949,0.000676,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.050024,0.076009,-0.046805,-0.041071,-0.046774,-0.001724,0.053536,34
3,0.081745,0.009819,0.013862,0.001011,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377724,0.479574,0.317907,0.338157,0.324423,0.367557,0.059735,25
4,0.090645,0.007195,0.037310,0.000690,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004135,0.013210,-0.103428,-0.095408,-0.101569,-0.056612,0.053448,36
5,0.077714,0.006437,0.014749,0.000715,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054577,0.071249,-0.046156,-0.024590,-0.049471,0.001122,0.051442,31
6,0.101166,0.012209,0.018726,0.000803,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049754,0.076446,-0.046990,-0.040903,-0.046771,-0.001693,0.053617,33
7,0.079506,0.004659,0.014261,0.000720,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377724,0.479574,0.317907,0.338157,0.324423,0.367557,0.059735,25
8,0.084527,0.006856,0.036707,0.002051,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300124,0.339544,0.174257,0.217017,0.183337,0.242856,0.065642,29
9,0.080068,0.006544,0.015258,0.001539,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.537814,0.574688,0.470001,0.532987,0.425034,0.508105,0.053456,22
10,0.097065,0.009391,0.017920,0.000680,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.482712,0.560842,0.433137,0.449720,0.431324,0.471547,0.048307,23
11,0.087631,0.011829,0.013777,0.000580,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584840,0.656088,0.553185,0.577115,0.547448,0.583735,0.038807,19
12,0.091610,0.001223,0.034755,0.003000,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.300606,0.338790,0.174699,0.216705,0.183330,0.242826,0.065439,30
13,0.077359,0.006410,0.015546,0.002256,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.534189,0.579262,0.467718,0.534956,0.425072,0.508240,0.054754,21
14,0.092588,0.003947,0.017604,0.000829,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.481175,0.561849,0.429295,0.451834,0.431336,0.471098,0.049065,24
15,0.082899,0.009116,0.013620,0.000596,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584840,0.656088,0.553185,0.577115,0.547448,0.583735,0.038807,19
16,0.103500,0.003787,0.036479,0.000741,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.731988,0.743653,0.686787,0.715193,0.644532,0.704430,0.035532,12
17,0.102896,0.005148,0.014638,0.000753,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.830806,0.806043,0.799112,0.802509,0.739945,0.795683,0.030020,7
18,0.110497,0.007253,0.017952,0.000588,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.323851,0.371445,0.287282,0.286805,0.351347,0.324146,0.033854,27
19,0.101903,0.007099,0.014461,0.001583,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.604973,0.589001,0.623195,0.538195,0.617342,0.594541,0.030513,17
20,0.115779,0.012365,0.039633,0.002969,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.732239,0.743319,0.687028,0.715059,0.644529,0.704435,0.035467,11
21,0.114947,0.009982,0.014516,0.000909,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.829390,0.805648,0.798663,0.802669,0.739952,0.795264,0.029659,8
22,0.101863,0.002985,0.017692,0.000325,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.328341,0.386884,0.216176,0.287478,0.351327,0.314041,0.058624,28
23,0.102017,0.007128,0.014205,0.000812,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.604973,0.589001,0.623195,0.538195,0.617342,0.594541,0.030513,17
24,0.111247,0.005020,0.034440,0.001539,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.816190,0.779806,0.791733,0.791076,0.732585,0.782278,0.027540,10
25,0.185629,0.034150,0.013938,0.000235,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.847468,0.808587,0.813767,0.803786,0.755123,0.805746,0.029596,3
26,0.103517,0.008004,0.018814,0.002392,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.445302,-0.511012,-0.493784,-0.461297,-0.099723,-0.402223,0.153017,37
27,0.121563,0.006944,0.013391,0.000116,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605615,0.583248,0.697406,0.532387,0.681584,0.620048,0.061673,15
28,0.109159,0.006452,0.035067,0.000976,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.816457,0.779685,0.791839,0.790950,0.732583,0.782303,0.027609,9
29,0.188515,0.039292,0.015237,0.001754,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.847539,0.808183,0.813734,0.803711,0.755123,0.805658,0.029608,4
30,0.110213,0.004965,0.018265,0.000810,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.616220,-0.532822,-0.478194,-0.542484,-0.102534,-0.454451,0.181367,38
31,0.129695,0.015480,0.014241,0.001175,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605615,0.583248,0.697406,0.532387,0.681584,0.620048,0.061673,15
32,0.128589,0.007761,0.035999,0.001382,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.829220,0.791264,0.810701,0.809750,0.742128,0.796613,0.029771,6
33,0.237804,0.073711,0.014763,0.000633,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.850124,0.806758,0.814590,0.804422,0.757864,0.806752,0.029455,1
34,0.113358,0.007480,0.018155,0.000785,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.754076,-2.044957,-1.699509,-1.914567,-1.035870,-1.689796,0.348857,40
35,0.143595,0.012151,0.014397,0.001521,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657721,0.583243,0.697893,0.529476,0.655869,0.624840,0.060341,13
36,0.119310,0.009261,0.035946,0.001198,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.829352,0.791147,0.810772,0.809730,0.742127,0.796625,0.029809,5
37,0.216247,0.041316,0.012463,0.002357,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.850157,0.806802,0.814553,0.804154,0.757866,0.806706,0.029467,2
38,0.108637,0.004678,0.018536,0.000869,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.682090,-1.830750,-1.676185,-1.941103,-1.036223,-1.633270,0.314468,39
39,0.129844,0.005893,0.009670,0.001562,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657721,0.583243,0.697893,0.529476,0.655869,0.624840,0.060341,13

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 35
BMI: 36
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣,change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[5797770.04019588]